version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/web
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    links:
      - db
      - redis
      - smtp

  db:
    # Use same version of postgres as we're currently using elsewhere
    # TODO: Upgrade to postgres 13 which we are now using in production
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=cuttlefish
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  smtp:
    build:
      context: .
      dockerfile: dockerfiles/web
    command: bundle exec rake cuttlefish:smtp
    volumes:
      - .:/app:cached
      # This needs to share the directory containing email content between
      # smtp server and workers
      - ./tmp/emails:/tmp:cached
    ports:
      - "2525:2525"

  redis:
    image: redis:4.0

  worker:
    build:
      context: .
      dockerfile: dockerfiles/web
    command: bundle exec sidekiq
    volumes:
      - .:/app:cached
      # This needs to share the directory containing email content between
      # smtp server and workers
      - ./tmp/emails:/tmp:cached
    links:
      - db
      - redis
      - postfix

  postfix:
    image: juanluisbaptiste/postfix
    environment:
      - SMTP_SERVER=mailcatcher
      - SMTP_PORT=1025
      # The username and password are actually ignore by mailcatcher but need
      # to be set to keep this container happy
      - SMTP_USERNAME=foo@bar.com
      - SMTP_PASSWORD=XXXXXXXX
      - SERVER_HOSTNAME=cuttlefish.io
    volumes:
      - ./postfix_log:/var/log:cached
    links:
      - mailcatcher

  mailcatcher:
    build:
      context: .
      dockerfile: dockerfiles/mailcatcher
    ports:
      - "1080:1080"

  log:
    build:
      context: .
      dockerfile: dockerfiles/web
    command: bundle exec rake cuttlefish:log
    volumes:
      - .:/app:cached
      - ./postfix_log:/var/log:cached
    links:
      - db

volumes:
  postgres_data:
