version: '3'
services:
  web:
    image: senolnar/cuttlefish:0.0.1
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    links:
      - db
      - redis
      - smtp

  db:
    # Use same version of postgres as we're currently using elsewhere
    # TODO: Upgrade to postgres 13 which we are now using in production
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=cuttlefish
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  smtp:
    image: senolnar/cuttlefish:0.0.1
    command: bundle exec rake cuttlefish:smtp
    volumes:
      - .:/app:cached
      # This needs to share the directory containing email content between
      # smtp server and workers
      - ./tmp/emails:/tmp:cached
    ports:
      - "2525:2525"

  redis:
    image: redis:4.0

  worker:
    image: senolnar/cuttlefish:0.0.1
    command: bundle exec sidekiq
    volumes:
      - .:/app:cached
      # This needs to share the directory containing email content between
      # smtp server and workers
      - ./tmp/emails:/tmp:cached
    links:
      - db
      - redis
      - postfix

  postfix:
    image: juanluisbaptiste/postfix
    environment:
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      # The username and password are actually ignore by mailcatcher but need
      # to be set to keep this container happy
      - SMTP_USERNAME=shagames42@gmail.com
      - SMTP_PASSWORD="xxxxx"
      - SERVER_HOSTNAME=cuttlefish.io
    volumes:
      - ./postfix_log:/var/log:cached

  log:
    image: senolnar/cuttlefish:0.0.1
    command: bundle exec rake cuttlefish:log
    volumes:
      - .:/app:cached
      - ./postfix_log:/var/log:cached
    links:
      - db

volumes:
  postgres_data:
