name: Build and Publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  docker:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          docker buildx build --push \
            --tag satac/cuttlefish:${{steps.tag.outputs.tag}} \
            --platform linux/amd64,linux/arm/v7,linux/arm64 . -f dockerfiles/web