name: Build and Publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install V8
        run: | 
          sudo apt install libcurl4-openssl-dev
          sudo apt install libv8-dev

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfiles/web
          push: true
          platforms: linux/amd64,linux/arm64
          tags: satac/cuttlefish:latest, satac/cuttlefish:${{steps.tag.outputs.tag}}